version: '3'
services:
  apache:
    image: php:8.0-apache
    ports:
      - "80:80"
    volumes:
      - /Users/Lenovo/OneDrive/Pulpit/ZombiePHP/ZombieGame/Apache/apache.conf # Montowanie pliku konfiguracyjnego Apache
      - /Users/Lenovo/OneDrive/Pulpit/ZombiePHP/ZombieGame/index.php  # Montowanie katalogu z kodem źródłowym PHP
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ZombieSymulation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - mynetwork

networks:
  mynetwork:
