version: '3'

services:
  web:
    image: httpd:latest
    ports:
      - "80:80"


    volumes:
    - C:/Users/Lenovo/OneDrive/Pulpit/ZombiePHP/ZombieGame/index.php

    depends_on:
      - db

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  db:
    image: httpd:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DANE
